name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Rename Artifacts
        shell: pwsh
        run: |
          Copy-Item target/x86_64-pc-windows-msvc/release/steamstubbed_standalone.dll target/x86_64-pc-windows-msvc/release/version.dll
          Copy-Item target/x86_64-pc-windows-msvc/release/steamstubbed_standalone.dll target/x86_64-pc-windows-msvc/release/winmm.dll

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: steam-stubbed
          path: |
            target/x86_64-pc-windows-msvc/release/version.dll
            target/x86_64-pc-windows-msvc/release/winmm.dll
